String s =  "<head>"
            "<title>Soldered Inkplate e-paper Display</title>"
            "<style type='text/css'>"
            "body {"
            "  font-family: Arial, sans-serif;"
            "  display: flex;"
            "  justify-content: center;"
            "  align-items: center;"
            "  height: 100vh;"
            "  margin: 0;"
            "  background-color: #f4f4f9;"
            "}"
            "form {"
            "  text-align: center;"
            "  background-color: #ffffff;"
            "  padding: 20px;"
            "  border-radius: 10px;"
            "  box-shadow: 0 4px 8px rgba(0,0,0,0.1);"
            "}"
            "textarea {"
            "  width: 100%;"
            "  max-width: 300px;"
            "  height: 100px;"
            "  font-size: 16px;"
            "  padding: 10px;"
            "  margin-top: 10px;"
            "  border-radius: 5px;"
            "  border: 1px solid #ccc;"
            "}"
            "t1 {"
            "  display: block;"
            "  font-size: 1.5em;"
            "  font-weight: bold;"
            "  margin-bottom: 10px;"
            "}"
            "input[type='submit'] {"
            "  background-color: #4CAF50;" /* Green */
            "  color: white;"
            "  padding: 15px 20px;"
            "  margin-top: 10px;"
            "  border: none;"
            "  border-radius: 5px;"
            "  cursor: pointer;"
            "  font-size: 16px;"
            "}"
            "input[type='submit']:hover {"
            "  background-color: #45a049;" /* Darker green */
            "}"
            "</style>"
           "</head>"
           "<body>"
           "<form action='/string/' method='get' target='_self'>"
           "<t1>Let's get busy</t1><br>"
           "<textarea placeholder='Add a task' autofocus maxlength='100' rows='7' cols='30' name='input1'></textarea><br>"
           "<input type='submit' value='Submit'>"
           "</form>"
           "</body>";
